
"""
infrastructure-product API

Backend service for the appliedAI infrastructure product

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.api.job_management_api import JobManagementApi


class TestJobManagementApi(unittest.TestCase):
    """JobManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobManagementApi()

    def tearDown(self) -> None:
        pass

    def test_logs_jobs_uid_logs_get(self) -> None:
        """Test case for logs_jobs_uid_logs_get

        Logs
        """
        pass

    def test_status_jobs_uid_status_get(self) -> None:
        """Test case for status_jobs_uid_status_get

        Status
        """
        pass

    def test_submit_job_jobs_post(self) -> None:
        """Test case for submit_job_jobs_post

        Submit Job
        """
        pass


if __name__ == "__main__":
    unittest.main()
