"""
infrastructure-product API

Backend service for the appliedAI infrastructure product

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.create_job_model import CreateJobModel


class TestCreateJobModel(unittest.TestCase):
    """CreateJobModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateJobModel:
        """Test CreateJobModel
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateJobModel`
        """
        model = CreateJobModel()
        if include_optional:
            return CreateJobModel(
                name = '',
                file = '',
                image_ref = '',
                mode = 'local',
                options = openapi_client.models.job_options.JobOptions(
                    resources = openapi_client.models.resource_options.ResourceOptions(
                        memory = '',
                        cpu = '',
                        gpu = 56, ),
                    scheduling = openapi_client.models.scheduling_options.SchedulingOptions(
                        priority_class = '',
                        queue_name = '', ),
                    labels = {
                        'key' : ''
                        }, ),
                submission_context = openapi_client.models.submission_context.Submission Context()
            )
        else:
            return CreateJobModel(
                name = '',
                file = '',
                image_ref = '',
                mode = 'local',
                options = openapi_client.models.job_options.JobOptions(
                    resources = openapi_client.models.resource_options.ResourceOptions(
                        memory = '',
                        cpu = '',
                        gpu = 56, ),
                    scheduling = openapi_client.models.scheduling_options.SchedulingOptions(
                        priority_class = '',
                        queue_name = '', ),
                    labels = {
                        'key' : ''
                        }, ),
        )
        """

    def testCreateJobModel(self):
        """Test CreateJobModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
