
"""
infrastructure-product API

Backend service for the appliedAI infrastructure product

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.job_options import JobOptions


class TestJobOptions(unittest.TestCase):
    """JobOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobOptions:
        """Test JobOptions
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `JobOptions`
        """
        model = JobOptions()
        if include_optional:
            return JobOptions(
                resources = openapi_client.models.resource_options.ResourceOptions(
                    memory = '',
                    cpu = '',
                    gpu = 56, ),
                scheduling = openapi_client.models.scheduling_options.SchedulingOptions(
                    priority_class = '',
                    queue_name = '', ),
                labels = {
                    'key' : ''
                    }
            )
        else:
            return JobOptions(
        )
        """

    def testJobOptions(self):
        """Test JobOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
