"""
infrastructure-product API

Backend service for the appliedAI infrastructure product

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.workload_identifier import WorkloadIdentifier


class TestWorkloadIdentifier(unittest.TestCase):
    """WorkloadIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkloadIdentifier:
        """Test WorkloadIdentifier
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WorkloadIdentifier`
        """
        model = WorkloadIdentifier()
        if include_optional:
            return WorkloadIdentifier(
                group = '',
                version = '',
                kind = '',
                namespace = '',
                uid = ''
            )
        else:
            return WorkloadIdentifier(
                group = '',
                version = '',
                kind = '',
                namespace = '',
                uid = '',
        )
        """

    def testWorkloadIdentifier(self):
        """Test WorkloadIdentifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
