# coding: utf-8

"""
infrastructure-product API

Backend service for the appliedAI infrastructure product

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictStr
from typing_extensions import Self

from jobs import JobOptions
from jobs.types import DictSerializable, ExecutionMode, JsonSerializable


class CreateJobModel(DictSerializable, JsonSerializable, BaseModel):
    """
    CreateJobModel
    """  # noqa: E501

    name: StrictStr
    file: StrictStr
    image_ref: StrictStr
    mode: ExecutionMode
    options: JobOptions
    submission_context: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = [
        "name",
        "file",
        "image_ref",
        "mode",
        "options",
        "submission_context",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))
