apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "jobq-server.fullname" . }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 256Mi
